set nocompatible

if has("win16") || has("win32")
    let plugpath="~/vimfiles/plugged"
    set gfn=Cascadia\ Code\ NF:h9
    set shell=pwsh.exe
    set shellcmdflag=-NoLogo\ -NoProfile\ -NonInteractive\ -command
else
    set viminfo+=n~/.config/vim/viminfo
    let plugpath="~/.config/vim/plugged"

    if has("gui_running")
        set gfn=Cascadia\ Code\ NF\ 9
    endif             

endif

call plug#begin(plugpath)
Plug 'sainnhe/gruvbox-material'
Plug 'sainnhe/everforest'
Plug 'nordtheme/vim'
Plug 'catppuccin/vim', { 'as': 'catppuccin' }
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'sheerun/vim-polyglot'
Plug 'NoahTheDuke/vim-just'
Plug 'pearofducks/ansible-vim'
Plug 'dense-analysis/ale'
Plug 'mcchrish/nnn.vim'
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
call plug#end()

if has("gui_running")
    set guioptions-=T
    set guioptions-=e
    set guioptions-=r
    set guioptions-=R
    set guioptions-=l
    set guioptions-=L
    set lines=60
    set columns=150
endif             

set t_co=256

if exists("$TMUX")
    set notermguicolors
else

    if exists('+termguicolors')
        let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
        let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
        set termguicolors
    endif

endif

let g:airline_powerline_fonts = 1

let g:theme_file = expand('~/.config/vim/theme.vim')

if filereadable(g:theme_file)
    execute 'source ' . g:theme_file
endif

augroup ThemeSync
    autocmd!
    autocmd FocusGained * if filereadable(g:theme_file) | execute 'source ' . g:theme_file | endif
augroup END

let g:ale_linters = { "python": ["ruff"] }
let g:ale_fixers = { "python": ["ruff"] }

autocmd BufNewFile,BufRead *.asm set filetype=nasm

set encoding=utf8
set ffs=unix,dos,mac

set number
set laststatus=2

set hlsearch
set ignorecase
set smartcase
set incsearch

set autoindent
set copyindent

set noswapfile
set tabstop=4
set shiftwidth=4
set expandtab
set noshowmode
set noerrorbells
syntax on
