text/html w3m -T text/html -dump %pistol-filename%
text/csv visidata %pistol-filename%
fpath .*\.md leaf %pistol-filename%
text/* bat --paging always %pistol-filename%
inode/directory tree -L 3 -C -F --dirsfirst --noreport %pistol-filename%
application/x-bittorrent transmission-show -D -T %pistol-filename%
application/x-rar unrar l -idc- %pistol-filename%
application/vnd.openxmlformats-officedocument.spreadsheetml.sheet xleak %pistol-filename%
image/* sh: timg %pistol-filename% | bat -p
fpath .*\.tgz$ tar tvf %pistol-filename%
