fpath .*\.md glow -p %pistol-filename%
text/html w3m -T text/html -dump %pistol-filename%
text/csv visidata %pistol-filename%
text/* bat %pistol-filename%
inode/directory tree -L 3 -C -F --dirsfirst --noreport %pistol-filename%
application/pdf sh: pdftotext -layout %pistol-filename% - | tr -d '\f' | bat --color=always --style=plain
application/x-bittorrent transmission-show -D -T %pistol-filename%
application/x-rar unrar l -idc- %pistol-filename%
application/vnd.openxmlformats-officedocument.spreadsheetml.sheet xleak %pistol-filename%
application/vnd.sqlite3 sh: litecli -e .tables -t %pistol-filename% | bat --style=plain
application/json bat --color=always --style=plain %pistol-filename%
application/x-ndjson bat --color=always --style=plain %pistol-filename%
image/* sh: timg %pistol-filename% | bat --style=plain
video/* sh: mpv %pistol-filename%
fpath .*\.tgz$ tar tvf %pistol-filename%
